# Site settings
title: Finbarr Brady
email: finbarr@finbarrbrady.com
description: > # this means to ignore newlines until "baseurl:"
  I like cake. Welcome to another website by myself, Finbarr Brady
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fbradyirl.github.io" # the base hostname & protocol for your site
twitter_username: finbarrbrady
github_username:  fbradyirl

# Build settings
markdown: kramdown
